version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
         name: Check Files
         command: ls -al
         
  run-tests:
    working_directory: ~/data-reliability-stability
    executor: python/default
    steps:
      - checkout
      - run: 
         name: Install Pytest
         command: pip install -U pytest
      - run:
         name: Install Pandas
         command: pip install pandas
      - run: 
         name: Install Pathlib
         command: pip install pathlib
      - run:
         name: Install Reliability Stability Package
         command: pip install reliability-stability-calc
         
      - run:
         name: Run Tests
         command: |
          mkdir tests/test-results
          pytest ./tests --junitxml=test-results/junit.xml
      - store_test_results:
         path: test-results

workflows:
  main:
    jobs:
      - build-and-test
      - run-tests
